### ISSUE TITLE
Component does nothing !?

### ISSUE THREAD

**Issue by emmguyot-adscom** [gretzky/react-native-android-wake-lock#3]
I've created a very small app to test this component but the device always locks and never wake up

My code :
```
componentDidMount() {
      console.log("did mount");
      setWakeLock.then( () => {
      setTimeout(() => {
        console.log("timeout");
        setWakeLock.then(
            () => {
              console.log("preAlerte");
              alert("Affichage on");
              releaseWakeLock.then( () => { console.log("released") } );
            }
          );
      }, 5*60000);
    });
  }
```

While running the app, I get no error but the device gets locked. And when I manually unlock it, I see the logs and the alert.
I expected that the device doesn't get locked and, after 5 minutes, the alert is shown.

My device : Samsung S10+ with Android 10

**Comment by flogy** [comment]
Correct me if I'm wrong, but as far as I understand, wake locks are only keeping the CPU from stopping. The device will get locked and the screen will be switched off anyways. See: https://developer.android.com/training/scheduling/wakelock#cpu

To prevent the screen from going black (at least while your app is running) you can use [react-native-keep-awake](https://www.npmjs.com/package/react-native-keep-awake).

**Comment by vineyardbovines** [comment]
@flogy is correct here. Closing because this is a non issue.
